version: "3.9"

services:

  postgres-academico:
    image: postgres:15
    container_name: postgres-academico
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: academico
    ports:
      - "5432:5432"

  academico-service:
    container_name: academico-service
    build: .

    depends_on:
      - postgres-academico
    ports:
      - "8081:8081"
